### ISSUE TITLE
Crash with latest 1.18.2 in my modpack. 

### ISSUE THREAD

**Issue by sherpascott** [theishiopian/Parrying#44]
[crash-2022-07-27_01.59.20-client.txt](https://github.com/theishiopian/Parrying/files/9196420/crash-2022-07-27_01.59.20-client.txt)

Is there maybe mods I could remove to fix? Also how do you even understand these I've tried for so long and I still don't lol

Thanks so much!

**Comment by woodgoldtwo** [comment]
i have the same problem

**Comment by theishiopian** [comment]
Try updating your forge to the latest version.

Crash reports are not hard to read. 

---- Minecraft Crash Report ----
// This doesn't make any sense!

This part is just the start of the crash log

Time: 7/27/22, 1:59 AM
Description: Initializing game

This describes what the problem is. Usually this description is useless

java.lang.NoSuchFieldError: ATTACK_RANGE

THIS is the actual problem. No such field error means java couldnt find a field called "attack range".

at com.theishiopian.parrying.Items.SpearItem.LazyModifiers(SpearItem.java:141) ~[parrying-1.18.2-2.5.2.jar%23199!/:2.5.2] {re:classloading}
	at com.theishiopian.parrying.Items.LazyItem.m_7167_(LazyItem.java:39) ~[parrying-1.18.2-2.5.2.jar%23199!/:2.5.2] {re:classloading}
	at... (Continues for like a million years what the fuck aaaaaaaah)

This is the "stacktrace", it traces the problem to the exact line of code where a problem was detected. This CAN be helpful, but isn't always useful.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

This part is basically stacktrace 2 electric boogaloo

The rest is largely unhelpful most of the time. Its mostly the mod list and system specs.

**Comment by sherpascott** [comment]
Thanks a ton man!
When you say update forge I assume you mean the version? Like forge 40.1.0. The only issue is I believe if I update then most of my mods won’t work because they were made for 40.1.0. I might be wrong. 

Would maybe using an earlier alpha version of parrying make it compatible with my forge version?

**Comment by theishiopian** [comment]
Yes, the version, sorry. Try 40.1.51, thats the one that I develop on. Don't use the earlier alphas, quivers don't work on those.

**Comment by theishiopian** [comment]
Does this go away if you update forge?

**Comment by sherpascott** [comment]
I tried but all the other mods don’t work when I update forge. Sorry I would love to use parrying but I’ve spent too much time on my pack already and id have to remake it from scratch to solve the issue

**Comment by theishiopian** [comment]
Well, there's no other fix I know of, sorry.
