### ISSUE TITLE
Flails are broken (Extreme DPS)

### ISSUE THREAD

**Issue by Looxond** [theishiopian/Parrying#49]
https://user-images.githubusercontent.com/29359853/183713871-da4d2999-be8e-46e1-8690-2f09b49216e3.mp4

**Comment by Looxond** [comment]
Fun fact: Due to the extreme DPS people in my server found a way to melt armor & kill everything in less than 5 seconds, im glad that they removed sharpness from flails because back then it was even worse

**Comment by theishiopian** [comment]
Looks like another balancing pass is in order.

**Comment by theishiopian** [comment]
So, after finally getting a chance to work on this again, it seems this issue is actually due to a bug where attack strength isn't considered by AP weapons. Maces and hammers have a similar issue, its just more noticeable on the flail since people naturally attack faster with it. Next update will have fixed attack strength math.
