### ISSUE TITLE
[Suggestion] A lot of ideas. 

### ISSUE THREAD

**Issue by Happy1speed** [theishiopian/Parrying#57]
I Understand that these might not be possible or in the spirit of the mod and its completely fine if that is the case.
But I do hope that some of these concepts are noteworthy enough to add in the future or give you a spark of inspiration and a good idea.

------GAME MECHANICS------

Satisfying swinging sounds (like the flail's) for all weapons. 
Maybe drawing noises for scrolling onto a weapon in the hotbar.
(Seriously, it's really satisfying to use the flail and to have a unique swing sound for all of them would be amazing.)

A sort of loyalty for thrown spears and daggers. 
Player: gets a netherite spear, enchants it with sharpness and unbreaking.
Player: Misses their target in the nether while throwing their spear, only to have it fly into a lava lake.
The spear won't burn in the lava since its netherite but it is now lost.
Players won't throw their enchanted daggers and spears if they can lose them by missing their target.

Some way to increase your defense meter so that it scales better with blocking more powerful later game weapon tiers.
Currently weapons in the mid-late game drain the parry meter at an alarming rate and parrying should scale with better gear.

Bludgeoning weapons should have less armor piercing from the start and can be upgraded to be given more later in the game, making them scale better alongside sharpness.
Ways to give more armor piercing could include an enchantment or a way to add some extra material onto them via the smithing table.

Arrows shot from a full drawn punch bow disable shields for a few seconds.

instant shield activation. (does this already exist in parry this?)

Better axe scaling. Instead of the current vanilla system, axes would stay the same attack speed and gain more damage per tier.
Axes should also not lose 2x as much durability from attacking an entity.

multishot crossbows can act like shotguns and have multiple arrows hit the same entity. (Right now, invulnerability ticks make the other two bounce off.)
I think there is also room for multishot 2 and 3, each firing more 3 more arrows.

A "back-shield" that you can wear that disables or majorly reduces backstabbing damage. This would take up your chest plate slot and only give 4 armor points.
Could also make arrows that hit your back bounce off. Great for countering people with backstabbing daggers or sneak-attacks.

Disabling random player arrow inaccuracy. 
It's really annoying that you can shoot an arrow, have it perfectly lined up, and still have it miss because of the randomness.

Tridents get half a block more reach. They're fairly rare and it makes sense.

Traps? A sticky trap maybe? (Non-full block that looks like the slime on a sticky piston head and slows down things that step on it. Instabreak block.)

Anvil repairing recipes for armor and weapons only cost 1 ingot (or something smaller like a nugget. Would need something like a diamond shard for diamond weapons) and no xp.
This will hopefully ease the need for mending/unbreaking until late game.

------WEAPON MECHANIC CONCEPTS------
These are just a collection of mechanics that could be used to make new weapons or spice up old ones.

Critical hit multiplier. example: a machete that deals 2x damage when critting instead of the
vanilla 1.5x (could also be used to nerf weapons by reducing crit damage)

Extra or less attack knockback. Examples: The 
Hammer does 1.5x as much knockback to targets. 
A sickle weapon that does less knockback than normal.

A Pan. Usable as a shield and a melee weapon. This allows for your offhand slot to be freed up.

Extra sweeping edge damage. sweeping attacks deal x amount of extra damage, making the playstyle for
that weapon less sprinting based.

Health based damage boost attribute? Example: Does 2 more damage while the target is above a certain percentage amount of health? This might be better as an enchantment.

----ENCHANTMENT IDEAS-----

Vertical knockback enchantment. (Only about a block max and incompatible with regular knockback enchantment.)

An enchantment (maybe called stalwart?) That makes parries deal no knockback to you and instead flings the opponent backwards a few blocks. Would have a cooldown of a few seconds.

An enchantment (could also be a weapon attribute for a rapier sword?) that gives you a short burst of attack speed when parrying an attack. 
Enchantment name could be something along the lines of flurry or rapidity.
As an enchantment this might be cool for daggers or swords.

++++++Ideas that might be considered too much of a shakeup, but I still think are good+++++++

Protection now only protects against melee attacks.
This will make people actually think about what kinds of protection they apply rather than just protection every time.

Magic Protection reduces magic damage by a moderate amount. Goes with the protection changes. 
Like other protection enchantments, you can't put this on armor that already has a protection group enchantment.

It's a lot. Thanks for reading!.

**Comment by theishiopian** [comment]
I LOVE this! Not all of these are appealing, but theres several great ideas.

-weapon sounds: great idea, would take a ton of work to find all the sounds, but not enough to make it not worth it. 
-loyalty for spears and daggers: i have been historically opposed to this, but you make a compelling argument. ill think aobut it
-defense meter increase: one thing i try to shy away from is making powerful gear TOO powerful. I want a player with higher skill to be able to defeat a player with a netherite sword using iron. however, this isnt a bad idea on paper. I might instead make it so strength potions buff your defense meter. 
-punch bows disable shields: this is a very unique idea, i think ill implement it.
-instant shield activation: im not sure what this means, can you elaborate?
-axes should lose durability against entities at the same rate as swords: yes
-multishot shotgun: parry this! already does this, if itsd not working please open a new issue for it.
-back shield: instead of a new item, a new chestplate enchantment makes more sense. a great idea
-disable random bow inaccuracy: jeb toyed with the idea of reducing spread to 0 but having it build up the longer you hold the bow down. I might do something similar
-trident reach: maybe, ill think about it
-traps: could be fun, maybe someday
-stalwart enchant: i might rework this into an upcoming feature, not sure
-protection rework: i might save ideas like this for an armor update, if i do one

Great stuff overall, I appreciate the suggestions!

**Comment by theishiopian** [comment]
I can confirm that a few of these are now coming to 2.6

**Comment by Happy1speed** [comment]
:D 
what I mean by instant shield activation is removing the quarter second delay that the shield has when you raise it. 
searching "minecraft shield delay" seems to give some good info on it.
